config/routes.rb
Rails.application.routes.draw do
  
  root to: "static#home"
  
  get "login", to: "static#login", as: :login
  
  post "sessions", to: "session#create", as: :new_session
  
  delete "sessions", to: "session#destroy", as: :logout


  get "/auth/google_oauth2/callback", to: "session#google"
  
  resources :users, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :users, only: [:show] do
    resources :comments, only: [:edit, :update, :destroy]
  end
  
  resources :states, only: [:index]
  post "states", to: "state#search", as: :state_search
  resources :states, only: [:show] do
    resources :cities, only: [:index, :show]
  end
  
  resources :stores, only: [:show] do
    resources :comments, only: [:create], as: :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/city.rb
class City < ApplicationRecord
  validates :name, presence: true
  validates :state_id, presence: true
  
  belongs_to :state
  has_many :stores

  scope :search_zip, -> (zip){where("zip_code_list LIKE ?", "%#{zip},%") }

  def state_abb
    self.state.abb
  end

  def zip_codes
    self.zip_code_list.split(", ")
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @state = State.find(params[:state_id])
  end

  def show
    @city = City.find(params[:id])
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/index.html.erb
<h1><%= @state.name%> - <%= @state.abb %></h1>
<h3>We have record store listings for the following cities:</h3>
<div class="list">
<ul>
  <% @state.cities.each do |city| %>
  <li><%= link_to city.name, state_city_path(@state, city) %></li>
  <%= city.stores.count %> stores listed<br>
  <% end %>
</ul>
</div>

app/views/cities/show.html.erb
<h1><%= @city.name %> - <%= link_to @city.state_abb, state_cities_path(@city.state) %></h1>
<p>We have found the following record stores in this city:</p>
<div class="list">
<ul>
  <% @city.stores.each do |store| %>
  <li><%= link_to store.name, store %></li>
  <% end %>
</ul>
</div>